name: Fortuitious Scribbles
meta_description: "Niranjan's Blog"

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: ""
domain_name: ""
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
author_url: "https://niranjan-dev-portfolio.now.sh"
author: "CaelestisZ"